version: '3' # docker-composeのバージョン
services:
  server:
    build:
      # イメージを作るためのDockerfileがある場所
      context: . # Dockerfileのある場所
      dockerfile: Dockerfile
    container_name: <<ProjectName>>_server
    volumes:
      # ローカルのデータにコンテナのデータをマウントする。
      - ./<<SrcDirName>>:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app # デフォルトの作業ディレクトリを指定
    command: sh -c 'npm run start'
    environment:
      - CHOKIDAR_USEPOLLING=true # docker環境の中でホットリロードを有効にします。
    tty: true
    stdin_open: true
    ports:
      - "3010:3010" # 左がローカル、右がDocker内のポート